import { Router } from 'express';
import { showLogin, login, logout } from '../controllers/auth.controller.js';
import { showDashboard } from '../controllers/dashboard.controller.js';
import { csrfToken, verifyCsrf, requireAuth, requireGuest } from '../middleware/auth.js';
import { loginLimit } from '../middleware/login-limit.js';
import { requirePermission } from '../middleware/authorization.js';
import { academicYearRoutes } from './academic-years.js';
import { academicStructureRoutes } from './academic-structure.js';
import { studentRoutes } from './students.js';
import { teacherRoutes } from './teachers.js';
import { guardianRoutes } from './guardians.js';
import { enrollmentRoutes } from './enrollments.js';
import { teacherAssignmentRoutes } from './teacher-assignments.js';
import { attendanceRoutes } from './attendance.js';
import { examRoutes } from './exams.js';
import { resultRoutes } from './results.js';
import { feeRoutes } from './fees.js';
import { paymentRoutes } from './payments.js';
import { timetableRoutes } from './timetable.js';
import { noticeRoutes } from './notices.js';
import { reportRoutes } from './reports.js';

export function authRoutes(config) {
  const router = Router();
  router.get('/login', requireGuest, csrfToken, showLogin);
  router.post('/login', requireGuest, loginLimit(config.secret), verifyCsrf, login);
  router.get('/dashboard', requireAuth, requirePermission('dashboard.view'), csrfToken, showDashboard);
  router.use(academicYearRoutes);
  router.use(academicStructureRoutes);
  router.use(studentRoutes);
  router.use(teacherRoutes);
  router.use(guardianRoutes);
  router.use(enrollmentRoutes);
  router.use(teacherAssignmentRoutes);
  router.use(attendanceRoutes);
  router.use(examRoutes);
  router.use(resultRoutes);
  router.use(feeRoutes);
  router.use(paymentRoutes);
  router.use(timetableRoutes);
  router.use(noticeRoutes);
  router.use(reportRoutes);
  router.post('/logout', requireAuth, verifyCsrf, logout(config));
  return router;
}
