export const roleNames = ['super_admin', 'admin', 'teacher', 'student', 'guardian'];

export const defaultPermissions = [
  ['dashboard.view', 'View the dashboard'],
  ['academic_year.view', 'View academic years'],
  ['academic_year.create', 'Create academic years'],
  ['academic_year.edit', 'Edit academic years'],
  ['academic_structure.view', 'View classes, sections and subjects'],
  ['academic_structure.create', 'Create classes, sections and subjects'],
  ['academic_structure.edit', 'Edit classes, sections and subjects'],
  ['student.view', 'View students within the permitted scope'],
  ['student.create', 'Create students'],
  ['student.edit', 'Edit students within the permitted scope'],
  ['student.delete', 'Delete students within the permitted scope'],
  ['teacher.view', 'View teachers within the permitted scope'],
  ['teacher.create', 'Create teachers'],
  ['teacher.edit', 'Edit teachers within the permitted scope'],
  ['guardian.view', 'View guardians within the permitted scope'],
  ['guardian.create', 'Create guardians'],
  ['guardian.edit', 'Edit guardians within the permitted scope'],
  ['enrollment.view', 'View enrollments within the permitted scope'],
  ['enrollment.create', 'Create enrollments'],
  ['enrollment.edit', 'Edit enrollments'],
  ['teacher_assignment.view', 'View teacher assignments within the permitted scope'],
  ['teacher_assignment.create', 'Create teacher assignments'],
  ['teacher_assignment.edit', 'Edit teacher assignments'],
  ['attendance.view', 'View attendance within the permitted scope'],
  ['attendance.create', 'Record attendance within the permitted scope'],
  ['attendance.edit', 'Edit attendance within the permitted scope'],
  ['exam.view', 'View exams within the permitted scope'],
  ['exam.create', 'Create exams'],
  ['exam.edit', 'Edit exams'],
  ['result.view', 'View published results within the permitted scope'],
  ['result.create', 'Record results within the permitted scope'],
  ['result.edit', 'Edit results within the permitted scope'],
  ['fee.view', 'View fees within the permitted scope'],
  ['fee.create', 'Assign fees'],
  ['fee.edit', 'Edit fees'],
  ['payment.view', 'View payment history within the permitted scope'],
  ['payment.create', 'Record payments'],
  ['timetable.view', 'View timetables within the permitted scope'],
  ['timetable.create', 'Create timetable entries'],
  ['timetable.edit', 'Edit timetable entries'],
  ['notice.view', 'View notices within the permitted scope'],
  ['notice.create', 'Create notices'],
  ['notice.edit', 'Edit notices'],
  ['report.view', 'View operational reports'],
];

export const defaultRoles = [
  { _id: 'super_admin', name: 'Super Admin', permissions: [] },
  { _id: 'admin', name: 'Admin', permissions: defaultPermissions.map(([name]) => name) },
  { _id: 'teacher', name: 'Teacher', permissions: [
    'dashboard.view', 'student.view', 'teacher.view', 'enrollment.view', 'teacher_assignment.view', 'attendance.view', 'attendance.create', 'attendance.edit', 'exam.view', 'result.view', 'result.create', 'result.edit', 'timetable.view', 'notice.view',
  ] },
  { _id: 'student', name: 'Student', permissions: ['dashboard.view', 'student.view', 'enrollment.view', 'attendance.view', 'exam.view', 'result.view', 'fee.view', 'payment.view', 'timetable.view', 'notice.view'] },
  { _id: 'guardian', name: 'Guardian', permissions: ['dashboard.view', 'guardian.view', 'student.view', 'enrollment.view', 'attendance.view', 'exam.view', 'result.view', 'fee.view', 'payment.view', 'timetable.view', 'notice.view'] },
];
